// Aria Agent gRPC Protocol
// 基于 internal/cli/up.go 中的 REST API 数据结构设计
//
// 通信模式：
// - Controller 监听 :50051 (gRPC)
// - Agent 定期轮询 Sync()（5秒间隔）
// - 支持双向认证（TLS）

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: pkg/grpc/agentpb/aria-agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PublicKey        string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                      // WireGuard 公钥
	Endpoint         string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                                         // 监听地址 ":51820"
	PrivateIp        string                 `protobuf:"bytes,3,opt,name=private_ip,json=privateIp,proto3" json:"private_ip,omitempty"`                      // 内网 IP（可选）
	PublicIp         string                 `protobuf:"bytes,4,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`                         // 公网 IP
	Hostname         string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`                                         // 主机名
	RegisteredAt     int64                  `protobuf:"varint,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`            // 注册时间戳
	Token            string                 `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`                                               // 注册 Token
	AdvertisedRoutes []string               `protobuf:"bytes,8,rep,name=advertised_routes,json=advertisedRoutes,proto3" json:"advertised_routes,omitempty"` // Site-to-Site VPN 路由
	Region           string                 `protobuf:"bytes,9,opt,name=region,proto3" json:"region,omitempty"`                                             // 地域
	CustomerId       string                 `protobuf:"bytes,10,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`                  // 客户 ID
	// 能力检测
	RuntimeMode   string `protobuf:"bytes,11,opt,name=runtime_mode,json=runtimeMode,proto3" json:"runtime_mode,omitempty"`       // "kernel" or "ebpf"
	KernelVersion string `protobuf:"bytes,12,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"` // 内核版本
	HasAesni      bool   `protobuf:"varint,13,opt,name=has_aesni,json=hasAesni,proto3" json:"has_aesni,omitempty"`               // 是否支持 AES-NI
	MachineId     string `protobuf:"bytes,14,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`             // 机器稳定标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterRequest) GetPrivateIp() string {
	if x != nil {
		return x.PrivateIp
	}
	return ""
}

func (x *RegisterRequest) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRequest) GetAdvertisedRoutes() []string {
	if x != nil {
		return x.AdvertisedRoutes
	}
	return nil
}

func (x *RegisterRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegisterRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *RegisterRequest) GetRuntimeMode() string {
	if x != nil {
		return x.RuntimeMode
	}
	return ""
}

func (x *RegisterRequest) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *RegisterRequest) GetHasAesni() bool {
	if x != nil {
		return x.HasAesni
	}
	return false
}

func (x *RegisterRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

type RegisterResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AssignedIp            string                 `protobuf:"bytes,1,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"`                                       // 分配的 VPN IP
	MetricsPushGateway    string                 `protobuf:"bytes,2,opt,name=metrics_push_gateway,json=metricsPushGateway,proto3" json:"metrics_push_gateway,omitempty"`             // Prometheus Push Gateway URL
	NodeId                string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                                                   // 平台侧稳定节点身份
	RuntimeToken          string                 `protobuf:"bytes,4,opt,name=runtime_token,json=runtimeToken,proto3" json:"runtime_token,omitempty"`                                 // 运行期短期凭据
	RuntimeTokenExpiresAt int64                  `protobuf:"varint,5,opt,name=runtime_token_expires_at,json=runtimeTokenExpiresAt,proto3" json:"runtime_token_expires_at,omitempty"` // 运行期凭据过期时间戳
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}

func (x *RegisterResponse) GetMetricsPushGateway() string {
	if x != nil {
		return x.MetricsPushGateway
	}
	return ""
}

func (x *RegisterResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterResponse) GetRuntimeToken() string {
	if x != nil {
		return x.RuntimeToken
	}
	return ""
}

func (x *RegisterResponse) GetRuntimeTokenExpiresAt() int64 {
	if x != nil {
		return x.RuntimeTokenExpiresAt
	}
	return 0
}

type SyncRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PublicKey           string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                                 // 兼容字段：运行期按 public_key 查找节点
	NodeId              string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                                          // 优先字段：运行期按 node_id 查找节点
	AppliedStateVersion string                 `protobuf:"bytes,3,opt,name=applied_state_version,json=appliedStateVersion,proto3" json:"applied_state_version,omitempty"` // Agent 当前已应用的 desired state 版本
	ObservedState       string                 `protobuf:"bytes,4,opt,name=observed_state,json=observedState,proto3" json:"observed_state,omitempty"`                     // Agent 当前观测状态：applied / healthy / error / in_progress
	ObservedMessage     string                 `protobuf:"bytes,5,opt,name=observed_message,json=observedMessage,proto3" json:"observed_message,omitempty"`               // Agent 当前观测说明或错误信息
	PublicIp            string                 `protobuf:"bytes,6,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`                                    // Agent 观测到的真实公网 IPv4，不能是本地/VPC 地址
	Endpoint            string                 `protobuf:"bytes,7,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                                                    // Agent 对外可达 WireGuard 端点
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{2}
}

func (x *SyncRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SyncRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SyncRequest) GetAppliedStateVersion() string {
	if x != nil {
		return x.AppliedStateVersion
	}
	return ""
}

func (x *SyncRequest) GetObservedState() string {
	if x != nil {
		return x.ObservedState
	}
	return ""
}

func (x *SyncRequest) GetObservedMessage() string {
	if x != nil {
		return x.ObservedMessage
	}
	return ""
}

func (x *SyncRequest) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *SyncRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type SyncResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Peers                 []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`                                                                                                                    // WireGuard Peers 列表
	AssignedIp            string                 `protobuf:"bytes,2,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"`                                                                                        // 当前节点的 VPN IP
	LastUpdate            int64                  `protobuf:"varint,3,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`                                                                                       // 最后更新时间戳
	AclRules              []*ACLRule             `protobuf:"bytes,4,rep,name=acl_rules,json=aclRules,proto3" json:"acl_rules,omitempty"`                                                                                              // 防火墙 ACL 规则
	MetricsPushGateway    string                 `protobuf:"bytes,5,opt,name=metrics_push_gateway,json=metricsPushGateway,proto3" json:"metrics_push_gateway,omitempty"`                                                              // Prometheus Push Gateway URL
	QosRules              []*QoSRule             `protobuf:"bytes,6,rep,name=qos_rules,json=qosRules,proto3" json:"qos_rules,omitempty"`                                                                                              // QoS 限速规则
	BlacklistRules        []*BlacklistRule       `protobuf:"bytes,7,rep,name=blacklist_rules,json=blacklistRules,proto3" json:"blacklist_rules,omitempty"`                                                                            // 黑名单规则
	DesiredStateVersion   string                 `protobuf:"bytes,8,opt,name=desired_state_version,json=desiredStateVersion,proto3" json:"desired_state_version,omitempty"`                                                           // Controller 当前期望配置版本
	RuntimeToken          string                 `protobuf:"bytes,9,opt,name=runtime_token,json=runtimeToken,proto3" json:"runtime_token,omitempty"`                                                                                  // 刷新后的运行期凭据
	RuntimeTokenExpiresAt int64                  `protobuf:"varint,10,opt,name=runtime_token_expires_at,json=runtimeTokenExpiresAt,proto3" json:"runtime_token_expires_at,omitempty"`                                                 // 运行期凭据过期时间戳
	SnapshotComplete      bool                   `protobuf:"varint,11,opt,name=snapshot_complete,json=snapshotComplete,proto3" json:"snapshot_complete,omitempty"`                                                                    // 本轮同步快照是否完整
	DomainVersions        map[string]string      `protobuf:"bytes,12,rep,name=domain_versions,json=domainVersions,proto3" json:"domain_versions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 各控制面 domain 的版本
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{3}
}

func (x *SyncResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *SyncResponse) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}

func (x *SyncResponse) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

func (x *SyncResponse) GetAclRules() []*ACLRule {
	if x != nil {
		return x.AclRules
	}
	return nil
}

func (x *SyncResponse) GetMetricsPushGateway() string {
	if x != nil {
		return x.MetricsPushGateway
	}
	return ""
}

func (x *SyncResponse) GetQosRules() []*QoSRule {
	if x != nil {
		return x.QosRules
	}
	return nil
}

func (x *SyncResponse) GetBlacklistRules() []*BlacklistRule {
	if x != nil {
		return x.BlacklistRules
	}
	return nil
}

func (x *SyncResponse) GetDesiredStateVersion() string {
	if x != nil {
		return x.DesiredStateVersion
	}
	return ""
}

func (x *SyncResponse) GetRuntimeToken() string {
	if x != nil {
		return x.RuntimeToken
	}
	return ""
}

func (x *SyncResponse) GetRuntimeTokenExpiresAt() int64 {
	if x != nil {
		return x.RuntimeTokenExpiresAt
	}
	return 0
}

func (x *SyncResponse) GetSnapshotComplete() bool {
	if x != nil {
		return x.SnapshotComplete
	}
	return false
}

func (x *SyncResponse) GetDomainVersions() map[string]string {
	if x != nil {
		return x.DomainVersions
	}
	return nil
}

type PeerInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PublicKey        string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                       // WireGuard 公钥
	Endpoint         string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                                          // UDP 端点地址
	PrivateIp        string                 `protobuf:"bytes,3,opt,name=private_ip,json=privateIp,proto3" json:"private_ip,omitempty"`                       // 内网 IP
	PublicIp         string                 `protobuf:"bytes,4,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`                          // 公网 IP
	Region           string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`                                              // 地域
	VpcId            string                 `protobuf:"bytes,6,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`                                   // VPC ID
	Hostname         string                 `protobuf:"bytes,7,opt,name=hostname,proto3" json:"hostname,omitempty"`                                          // 主机名
	AssignedIp       string                 `protobuf:"bytes,8,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"`                    // VPN IP
	Role             string                 `protobuf:"bytes,9,opt,name=role,proto3" json:"role,omitempty"`                                                  // 角色
	AdvertisedRoutes []string               `protobuf:"bytes,10,rep,name=advertised_routes,json=advertisedRoutes,proto3" json:"advertised_routes,omitempty"` // Site-to-Site VPN 路由
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PeerInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *PeerInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PeerInfo) GetPrivateIp() string {
	if x != nil {
		return x.PrivateIp
	}
	return ""
}

func (x *PeerInfo) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *PeerInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PeerInfo) GetVpcId() string {
	if x != nil {
		return x.VpcId
	}
	return ""
}

func (x *PeerInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PeerInfo) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}

func (x *PeerInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PeerInfo) GetAdvertisedRoutes() []string {
	if x != nil {
		return x.AdvertisedRoutes
	}
	return nil
}

type ACLRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcNet        string                 `protobuf:"bytes,1,opt,name=src_net,json=srcNet,proto3" json:"src_net,omitempty"`     // 源 CIDR（如 "10.0.0.0/8"）
	DstNet        string                 `protobuf:"bytes,2,opt,name=dst_net,json=dstNet,proto3" json:"dst_net,omitempty"`     // 目标 CIDR（如 "192.168.0.0/16"）
	Protocol      uint32                 `protobuf:"varint,3,opt,name=protocol,proto3" json:"protocol,omitempty"`              // IP 协议（6=TCP, 17=UDP, 0=any）
	MinPort       uint32                 `protobuf:"varint,4,opt,name=min_port,json=minPort,proto3" json:"min_port,omitempty"` // 最小端口（0=any）
	MaxPort       uint32                 `protobuf:"varint,5,opt,name=max_port,json=maxPort,proto3" json:"max_port,omitempty"` // 最大端口（65535=any）
	Action        string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`                   // 动作：allow 或 deny
	Direction     string                 `protobuf:"bytes,7,opt,name=direction,proto3" json:"direction,omitempty"`             // 方向：ingress、egress、both
	Ports         string                 `protobuf:"bytes,8,opt,name=ports,proto3" json:"ports,omitempty"`                     // 端口 bitmap 规则（如 "80-82,443:0"）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACLRule) Reset() {
	*x = ACLRule{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACLRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACLRule) ProtoMessage() {}

func (x *ACLRule) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACLRule.ProtoReflect.Descriptor instead.
func (*ACLRule) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ACLRule) GetSrcNet() string {
	if x != nil {
		return x.SrcNet
	}
	return ""
}

func (x *ACLRule) GetDstNet() string {
	if x != nil {
		return x.DstNet
	}
	return ""
}

func (x *ACLRule) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *ACLRule) GetMinPort() uint32 {
	if x != nil {
		return x.MinPort
	}
	return 0
}

func (x *ACLRule) GetMaxPort() uint32 {
	if x != nil {
		return x.MaxPort
	}
	return 0
}

func (x *ACLRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ACLRule) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ACLRule) GetPorts() string {
	if x != nil {
		return x.Ports
	}
	return ""
}

type QoSRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIp         string                 `protobuf:"bytes,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`                          // 源 IP
	DstIp         string                 `protobuf:"bytes,2,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`                          // 目标 IP
	SrcPort       uint32                 `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`                   // 源端口
	DstPort       uint32                 `protobuf:"varint,4,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`                   // 目标端口
	Protocol      uint32                 `protobuf:"varint,5,opt,name=protocol,proto3" json:"protocol,omitempty"`                                // 协议
	BandwidthMbps uint64                 `protobuf:"varint,6,opt,name=bandwidth_mbps,json=bandwidthMbps,proto3" json:"bandwidth_mbps,omitempty"` // 带宽限制
	Direction     string                 `protobuf:"bytes,7,opt,name=direction,proto3" json:"direction,omitempty"`                               // 方向：ingress 或 egress
	RateBps       uint64                 `protobuf:"varint,8,opt,name=rate_bps,json=rateBps,proto3" json:"rate_bps,omitempty"`                   // 精确速率（bps）
	BurstBytes    uint64                 `protobuf:"varint,9,opt,name=burst_bytes,json=burstBytes,proto3" json:"burst_bytes,omitempty"`          // 突发字节数
	Priority      uint32                 `protobuf:"varint,10,opt,name=priority,proto3" json:"priority,omitempty"`                               // 优先级
	Mode          string                 `protobuf:"bytes,11,opt,name=mode,proto3" json:"mode,omitempty"`                                        // policing 或 shaping
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QoSRule) Reset() {
	*x = QoSRule{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QoSRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QoSRule) ProtoMessage() {}

func (x *QoSRule) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QoSRule.ProtoReflect.Descriptor instead.
func (*QoSRule) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{6}
}

func (x *QoSRule) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *QoSRule) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *QoSRule) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *QoSRule) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *QoSRule) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *QoSRule) GetBandwidthMbps() uint64 {
	if x != nil {
		return x.BandwidthMbps
	}
	return 0
}

func (x *QoSRule) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *QoSRule) GetRateBps() uint64 {
	if x != nil {
		return x.RateBps
	}
	return 0
}

func (x *QoSRule) GetBurstBytes() uint64 {
	if x != nil {
		return x.BurstBytes
	}
	return 0
}

func (x *QoSRule) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *QoSRule) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type BlacklistRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"` // src, dst, ports
	Cidr          string                 `protobuf:"bytes,2,opt,name=cidr,proto3" json:"cidr,omitempty"`   // CIDR for src/dst blacklist
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`  // Port for port blacklist
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlacklistRule) Reset() {
	*x = BlacklistRule{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlacklistRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistRule) ProtoMessage() {}

func (x *BlacklistRule) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistRule.ProtoReflect.Descriptor instead.
func (*BlacklistRule) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{7}
}

func (x *BlacklistRule) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *BlacklistRule) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *BlacklistRule) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type SyncConfigRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Peers          []*PeerConfig          `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`                                         // Peer 配置
	AclRules       []*ACLRule             `protobuf:"bytes,2,rep,name=acl_rules,json=aclRules,proto3" json:"acl_rules,omitempty"`                   // ACL 规则
	QosRules       []*QoSRule             `protobuf:"bytes,3,rep,name=qos_rules,json=qosRules,proto3" json:"qos_rules,omitempty"`                   // QoS 规则
	BlacklistRules []*BlacklistRule       `protobuf:"bytes,4,rep,name=blacklist_rules,json=blacklistRules,proto3" json:"blacklist_rules,omitempty"` // 黑名单规则
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncConfigRequest) Reset() {
	*x = SyncConfigRequest{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConfigRequest) ProtoMessage() {}

func (x *SyncConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConfigRequest.ProtoReflect.Descriptor instead.
func (*SyncConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{8}
}

func (x *SyncConfigRequest) GetPeers() []*PeerConfig {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *SyncConfigRequest) GetAclRules() []*ACLRule {
	if x != nil {
		return x.AclRules
	}
	return nil
}

func (x *SyncConfigRequest) GetQosRules() []*QoSRule {
	if x != nil {
		return x.QosRules
	}
	return nil
}

func (x *SyncConfigRequest) GetBlacklistRules() []*BlacklistRule {
	if x != nil {
		return x.BlacklistRules
	}
	return nil
}

type SyncConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncConfigResponse) Reset() {
	*x = SyncConfigResponse{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConfigResponse) ProtoMessage() {}

func (x *SyncConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConfigResponse.ProtoReflect.Descriptor instead.
func (*SyncConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{9}
}

func (x *SyncConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PeerConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PublicKey           string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Endpoint            string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AllowedIps          []string               `protobuf:"bytes,3,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	PersistentKeepalive uint32                 `protobuf:"varint,4,opt,name=persistent_keepalive,json=persistentKeepalive,proto3" json:"persistent_keepalive,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PeerConfig) Reset() {
	*x = PeerConfig{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerConfig) ProtoMessage() {}

func (x *PeerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerConfig.ProtoReflect.Descriptor instead.
func (*PeerConfig) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{10}
}

func (x *PeerConfig) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *PeerConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PeerConfig) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *PeerConfig) GetPersistentKeepalive() uint32 {
	if x != nil {
		return x.PersistentKeepalive
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{11}
}

func (x *HealthCheckRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Stats         *AgentStats            `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{12}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetStats() *AgentStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type AgentStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalPeers    uint64                 `protobuf:"varint,1,opt,name=total_peers,json=totalPeers,proto3" json:"total_peers,omitempty"`     // 总 Peer 数
	ActivePeers   uint64                 `protobuf:"varint,2,opt,name=active_peers,json=activePeers,proto3" json:"active_peers,omitempty"`  // 活跃 Peer 数
	CpuUsage      float64                `protobuf:"fixed64,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`          // CPU 使用率
	MemoryUsage   float64                `protobuf:"fixed64,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"` // 内存使用率
	TxBytes       uint64                 `protobuf:"varint,5,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`              // 发送字节数
	RxBytes       uint64                 `protobuf:"varint,6,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`              // 接收字节数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStats) Reset() {
	*x = AgentStats{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStats) ProtoMessage() {}

func (x *AgentStats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStats.ProtoReflect.Descriptor instead.
func (*AgentStats) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{13}
}

func (x *AgentStats) GetTotalPeers() uint64 {
	if x != nil {
		return x.TotalPeers
	}
	return 0
}

func (x *AgentStats) GetActivePeers() uint64 {
	if x != nil {
		return x.ActivePeers
	}
	return 0
}

func (x *AgentStats) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *AgentStats) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *AgentStats) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *AgentStats) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

type ReportStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Stats         *AgentStats            `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatsRequest) Reset() {
	*x = ReportStatsRequest{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatsRequest) ProtoMessage() {}

func (x *ReportStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatsRequest.ProtoReflect.Descriptor instead.
func (*ReportStatsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ReportStatsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReportStatsRequest) GetStats() *AgentStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type ReportStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatsResponse) Reset() {
	*x = ReportStatsResponse{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatsResponse) ProtoMessage() {}

func (x *ReportStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatsResponse.ProtoReflect.Descriptor instead.
func (*ReportStatsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ReportStatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`                                                    // 命令唯一ID
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`                                                                         // 命令类型: "sync", "restart", "config_reload", "health_check"
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 命令参数
	Timeout       int32                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`                                                                        // 超时时间（秒）
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`                                                                      // 优先级: 0=普通, 1=高, 2=紧急
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                   // 命令创建时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{16}
}

func (x *CommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *CommandRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *CommandRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CommandRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`                                                    // 命令唯一ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                                                           // pending, acknowledged, completed, failed
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                                                         // 状态消息或错误信息
	Result        map[string]string      `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 命令执行结果
	CompletedAt   int64                  `protobuf:"varint,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`                                             // 命令完成时间戳
	NodeId        string                 `protobuf:"bytes,6,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                                                             // 运行期稳定节点身份
	PublicKey     string                 `protobuf:"bytes,7,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                                                    // 兼容字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{17}
}

func (x *CommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandResponse) GetResult() map[string]string {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CommandResponse) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *CommandResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CommandResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type MetricsReportRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AgentId   string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // 兼容字段：历史上报身份（通常为 public_key）
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`           // 上报时间戳
	// 系统指标
	CpuUsage    float64 `protobuf:"fixed64,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`          // CPU 使用率 (0-100)
	MemoryUsage float64 `protobuf:"fixed64,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"` // 内存使用率 (0-100)
	MemoryTotal uint64  `protobuf:"varint,5,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`  // 总内存 (bytes)
	MemoryUsed  uint64  `protobuf:"varint,6,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`     // 已用内存 (bytes)
	DiskUsage   float64 `protobuf:"fixed64,7,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`       // 磁盘使用率 (0-100)
	DiskTotal   uint64  `protobuf:"varint,8,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`        // 总磁盘 (bytes)
	DiskUsed    uint64  `protobuf:"varint,9,opt,name=disk_used,json=diskUsed,proto3" json:"disk_used,omitempty"`           // 已用磁盘 (bytes)
	// 网络指标
	NetworkTxBytes   uint64 `protobuf:"varint,10,opt,name=network_tx_bytes,json=networkTxBytes,proto3" json:"network_tx_bytes,omitempty"`       // 发送字节数
	NetworkRxBytes   uint64 `protobuf:"varint,11,opt,name=network_rx_bytes,json=networkRxBytes,proto3" json:"network_rx_bytes,omitempty"`       // 接收字节数
	NetworkTxPackets uint64 `protobuf:"varint,12,opt,name=network_tx_packets,json=networkTxPackets,proto3" json:"network_tx_packets,omitempty"` // 发送包数
	NetworkRxPackets uint64 `protobuf:"varint,13,opt,name=network_rx_packets,json=networkRxPackets,proto3" json:"network_rx_packets,omitempty"` // 接收包数
	NetworkTxErrors  uint64 `protobuf:"varint,14,opt,name=network_tx_errors,json=networkTxErrors,proto3" json:"network_tx_errors,omitempty"`    // 发送错误数
	NetworkRxErrors  uint64 `protobuf:"varint,15,opt,name=network_rx_errors,json=networkRxErrors,proto3" json:"network_rx_errors,omitempty"`    // 接收错误数
	// WireGuard 指标
	WgTxBytes     uint64 `protobuf:"varint,16,opt,name=wg_tx_bytes,json=wgTxBytes,proto3" json:"wg_tx_bytes,omitempty"`             // WireGuard 发送字节数
	WgRxBytes     uint64 `protobuf:"varint,17,opt,name=wg_rx_bytes,json=wgRxBytes,proto3" json:"wg_rx_bytes,omitempty"`             // WireGuard 接收字节数
	WgPeerCount   uint32 `protobuf:"varint,18,opt,name=wg_peer_count,json=wgPeerCount,proto3" json:"wg_peer_count,omitempty"`       // WireGuard Peer 数量
	WgActivePeers uint32 `protobuf:"varint,19,opt,name=wg_active_peers,json=wgActivePeers,proto3" json:"wg_active_peers,omitempty"` // 活跃 Peer 数量
	// 自定义指标
	CustomMetrics map[string]float64 `protobuf:"bytes,20,rep,name=custom_metrics,json=customMetrics,proto3" json:"custom_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // 自定义指标键值对
	NodeId        string             `protobuf:"bytes,21,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                                                                                                  // 优先字段：运行期稳定节点身份
	PublicKey     string             `protobuf:"bytes,22,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                                                                                         // 兼容字段：当前节点 WireGuard 公钥
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsReportRequest) Reset() {
	*x = MetricsReportRequest{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReportRequest) ProtoMessage() {}

func (x *MetricsReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReportRequest.ProtoReflect.Descriptor instead.
func (*MetricsReportRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{18}
}

func (x *MetricsReportRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricsReportRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsReportRequest) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *MetricsReportRequest) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *MetricsReportRequest) GetMemoryTotal() uint64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *MetricsReportRequest) GetMemoryUsed() uint64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *MetricsReportRequest) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *MetricsReportRequest) GetDiskTotal() uint64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *MetricsReportRequest) GetDiskUsed() uint64 {
	if x != nil {
		return x.DiskUsed
	}
	return 0
}

func (x *MetricsReportRequest) GetNetworkTxBytes() uint64 {
	if x != nil {
		return x.NetworkTxBytes
	}
	return 0
}

func (x *MetricsReportRequest) GetNetworkRxBytes() uint64 {
	if x != nil {
		return x.NetworkRxBytes
	}
	return 0
}

func (x *MetricsReportRequest) GetNetworkTxPackets() uint64 {
	if x != nil {
		return x.NetworkTxPackets
	}
	return 0
}

func (x *MetricsReportRequest) GetNetworkRxPackets() uint64 {
	if x != nil {
		return x.NetworkRxPackets
	}
	return 0
}

func (x *MetricsReportRequest) GetNetworkTxErrors() uint64 {
	if x != nil {
		return x.NetworkTxErrors
	}
	return 0
}

func (x *MetricsReportRequest) GetNetworkRxErrors() uint64 {
	if x != nil {
		return x.NetworkRxErrors
	}
	return 0
}

func (x *MetricsReportRequest) GetWgTxBytes() uint64 {
	if x != nil {
		return x.WgTxBytes
	}
	return 0
}

func (x *MetricsReportRequest) GetWgRxBytes() uint64 {
	if x != nil {
		return x.WgRxBytes
	}
	return 0
}

func (x *MetricsReportRequest) GetWgPeerCount() uint32 {
	if x != nil {
		return x.WgPeerCount
	}
	return 0
}

func (x *MetricsReportRequest) GetWgActivePeers() uint32 {
	if x != nil {
		return x.WgActivePeers
	}
	return 0
}

func (x *MetricsReportRequest) GetCustomMetrics() map[string]float64 {
	if x != nil {
		return x.CustomMetrics
	}
	return nil
}

func (x *MetricsReportRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MetricsReportRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type MetricsReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsReportResponse) Reset() {
	*x = MetricsReportResponse{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReportResponse) ProtoMessage() {}

func (x *MetricsReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReportResponse.ProtoReflect.Descriptor instead.
func (*MetricsReportResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{19}
}

func (x *MetricsReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MetricsReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_grpc_agentpb_aria_agent_proto protoreflect.FileDescriptor

const file_pkg_grpc_agentpb_aria_agent_proto_rawDesc = "" +
	"\n" +
	"!pkg/grpc/agentpb/aria-agent.proto\x12\n" +
	"aria.agent\"\xcb\x03\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1d\n" +
	"\n" +
	"private_ip\x18\x03 \x01(\tR\tprivateIp\x12\x1b\n" +
	"\tpublic_ip\x18\x04 \x01(\tR\bpublicIp\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12#\n" +
	"\rregistered_at\x18\x06 \x01(\x03R\fregisteredAt\x12\x14\n" +
	"\x05token\x18\a \x01(\tR\x05token\x12+\n" +
	"\x11advertised_routes\x18\b \x03(\tR\x10advertisedRoutes\x12\x16\n" +
	"\x06region\x18\t \x01(\tR\x06region\x12\x1f\n" +
	"\vcustomer_id\x18\n" +
	" \x01(\tR\n" +
	"customerId\x12!\n" +
	"\fruntime_mode\x18\v \x01(\tR\vruntimeMode\x12%\n" +
	"\x0ekernel_version\x18\f \x01(\tR\rkernelVersion\x12\x1b\n" +
	"\thas_aesni\x18\r \x01(\bR\bhasAesni\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x0e \x01(\tR\tmachineId\"\xdc\x01\n" +
	"\x10RegisterResponse\x12\x1f\n" +
	"\vassigned_ip\x18\x01 \x01(\tR\n" +
	"assignedIp\x120\n" +
	"\x14metrics_push_gateway\x18\x02 \x01(\tR\x12metricsPushGateway\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12#\n" +
	"\rruntime_token\x18\x04 \x01(\tR\fruntimeToken\x127\n" +
	"\x18runtime_token_expires_at\x18\x05 \x01(\x03R\x15runtimeTokenExpiresAt\"\x84\x02\n" +
	"\vSyncRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x122\n" +
	"\x15applied_state_version\x18\x03 \x01(\tR\x13appliedStateVersion\x12%\n" +
	"\x0eobserved_state\x18\x04 \x01(\tR\robservedState\x12)\n" +
	"\x10observed_message\x18\x05 \x01(\tR\x0fobservedMessage\x12\x1b\n" +
	"\tpublic_ip\x18\x06 \x01(\tR\bpublicIp\x12\x1a\n" +
	"\bendpoint\x18\a \x01(\tR\bendpoint\"\xaf\x05\n" +
	"\fSyncResponse\x12*\n" +
	"\x05peers\x18\x01 \x03(\v2\x14.aria.agent.PeerInfoR\x05peers\x12\x1f\n" +
	"\vassigned_ip\x18\x02 \x01(\tR\n" +
	"assignedIp\x12\x1f\n" +
	"\vlast_update\x18\x03 \x01(\x03R\n" +
	"lastUpdate\x120\n" +
	"\tacl_rules\x18\x04 \x03(\v2\x13.aria.agent.ACLRuleR\baclRules\x120\n" +
	"\x14metrics_push_gateway\x18\x05 \x01(\tR\x12metricsPushGateway\x120\n" +
	"\tqos_rules\x18\x06 \x03(\v2\x13.aria.agent.QoSRuleR\bqosRules\x12B\n" +
	"\x0fblacklist_rules\x18\a \x03(\v2\x19.aria.agent.BlacklistRuleR\x0eblacklistRules\x122\n" +
	"\x15desired_state_version\x18\b \x01(\tR\x13desiredStateVersion\x12#\n" +
	"\rruntime_token\x18\t \x01(\tR\fruntimeToken\x127\n" +
	"\x18runtime_token_expires_at\x18\n" +
	" \x01(\x03R\x15runtimeTokenExpiresAt\x12+\n" +
	"\x11snapshot_complete\x18\v \x01(\bR\x10snapshotComplete\x12U\n" +
	"\x0fdomain_versions\x18\f \x03(\v2,.aria.agent.SyncResponse.DomainVersionsEntryR\x0edomainVersions\x1aA\n" +
	"\x13DomainVersionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x02\n" +
	"\bPeerInfo\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1d\n" +
	"\n" +
	"private_ip\x18\x03 \x01(\tR\tprivateIp\x12\x1b\n" +
	"\tpublic_ip\x18\x04 \x01(\tR\bpublicIp\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x15\n" +
	"\x06vpc_id\x18\x06 \x01(\tR\x05vpcId\x12\x1a\n" +
	"\bhostname\x18\a \x01(\tR\bhostname\x12\x1f\n" +
	"\vassigned_ip\x18\b \x01(\tR\n" +
	"assignedIp\x12\x12\n" +
	"\x04role\x18\t \x01(\tR\x04role\x12+\n" +
	"\x11advertised_routes\x18\n" +
	" \x03(\tR\x10advertisedRoutes\"\xd9\x01\n" +
	"\aACLRule\x12\x17\n" +
	"\asrc_net\x18\x01 \x01(\tR\x06srcNet\x12\x17\n" +
	"\adst_net\x18\x02 \x01(\tR\x06dstNet\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\rR\bprotocol\x12\x19\n" +
	"\bmin_port\x18\x04 \x01(\rR\aminPort\x12\x19\n" +
	"\bmax_port\x18\x05 \x01(\rR\amaxPort\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x1c\n" +
	"\tdirection\x18\a \x01(\tR\tdirection\x12\x14\n" +
	"\x05ports\x18\b \x01(\tR\x05ports\"\xba\x02\n" +
	"\aQoSRule\x12\x15\n" +
	"\x06src_ip\x18\x01 \x01(\tR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x02 \x01(\tR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x03 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x04 \x01(\rR\adstPort\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\rR\bprotocol\x12%\n" +
	"\x0ebandwidth_mbps\x18\x06 \x01(\x04R\rbandwidthMbps\x12\x1c\n" +
	"\tdirection\x18\a \x01(\tR\tdirection\x12\x19\n" +
	"\brate_bps\x18\b \x01(\x04R\arateBps\x12\x1f\n" +
	"\vburst_bytes\x18\t \x01(\x04R\n" +
	"burstBytes\x12\x1a\n" +
	"\bpriority\x18\n" +
	" \x01(\rR\bpriority\x12\x12\n" +
	"\x04mode\x18\v \x01(\tR\x04mode\"M\n" +
	"\rBlacklistRule\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x12\n" +
	"\x04cidr\x18\x02 \x01(\tR\x04cidr\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\"\xe9\x01\n" +
	"\x11SyncConfigRequest\x12,\n" +
	"\x05peers\x18\x01 \x03(\v2\x16.aria.agent.PeerConfigR\x05peers\x120\n" +
	"\tacl_rules\x18\x02 \x03(\v2\x13.aria.agent.ACLRuleR\baclRules\x120\n" +
	"\tqos_rules\x18\x03 \x03(\v2\x13.aria.agent.QoSRuleR\bqosRules\x12B\n" +
	"\x0fblacklist_rules\x18\x04 \x03(\v2\x19.aria.agent.BlacklistRuleR\x0eblacklistRules\"H\n" +
	"\x12SyncConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9b\x01\n" +
	"\n" +
	"PeerConfig\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\x03 \x03(\tR\n" +
	"allowedIps\x121\n" +
	"\x14persistent_keepalive\x18\x04 \x01(\rR\x13persistentKeepalive\"/\n" +
	"\x12HealthCheckRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"w\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x05stats\x18\x03 \x01(\v2\x16.aria.agent.AgentStatsR\x05stats\"\xc6\x01\n" +
	"\n" +
	"AgentStats\x12\x1f\n" +
	"\vtotal_peers\x18\x01 \x01(\x04R\n" +
	"totalPeers\x12!\n" +
	"\factive_peers\x18\x02 \x01(\x04R\vactivePeers\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\x01R\vmemoryUsage\x12\x19\n" +
	"\btx_bytes\x18\x05 \x01(\x04R\atxBytes\x12\x19\n" +
	"\brx_bytes\x18\x06 \x01(\x04R\arxBytes\"]\n" +
	"\x12ReportStatsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12,\n" +
	"\x05stats\x18\x02 \x01(\v2\x16.aria.agent.AgentStatsR\x05stats\"/\n" +
	"\x13ReportStatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x99\x02\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12>\n" +
	"\x06params\x18\x03 \x03(\v2&.aria.agent.CommandRequest.ParamsEntryR\x06params\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x05R\atimeout\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x02\n" +
	"\x0fCommandResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12?\n" +
	"\x06result\x18\x04 \x03(\v2'.aria.agent.CommandResponse.ResultEntryR\x06result\x12!\n" +
	"\fcompleted_at\x18\x05 \x01(\x03R\vcompletedAt\x12\x17\n" +
	"\anode_id\x18\x06 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"public_key\x18\a \x01(\tR\tpublicKey\x1a9\n" +
	"\vResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\a\n" +
	"\x14MetricsReportRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\x01R\vmemoryUsage\x12!\n" +
	"\fmemory_total\x18\x05 \x01(\x04R\vmemoryTotal\x12\x1f\n" +
	"\vmemory_used\x18\x06 \x01(\x04R\n" +
	"memoryUsed\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\a \x01(\x01R\tdiskUsage\x12\x1d\n" +
	"\n" +
	"disk_total\x18\b \x01(\x04R\tdiskTotal\x12\x1b\n" +
	"\tdisk_used\x18\t \x01(\x04R\bdiskUsed\x12(\n" +
	"\x10network_tx_bytes\x18\n" +
	" \x01(\x04R\x0enetworkTxBytes\x12(\n" +
	"\x10network_rx_bytes\x18\v \x01(\x04R\x0enetworkRxBytes\x12,\n" +
	"\x12network_tx_packets\x18\f \x01(\x04R\x10networkTxPackets\x12,\n" +
	"\x12network_rx_packets\x18\r \x01(\x04R\x10networkRxPackets\x12*\n" +
	"\x11network_tx_errors\x18\x0e \x01(\x04R\x0fnetworkTxErrors\x12*\n" +
	"\x11network_rx_errors\x18\x0f \x01(\x04R\x0fnetworkRxErrors\x12\x1e\n" +
	"\vwg_tx_bytes\x18\x10 \x01(\x04R\twgTxBytes\x12\x1e\n" +
	"\vwg_rx_bytes\x18\x11 \x01(\x04R\twgRxBytes\x12\"\n" +
	"\rwg_peer_count\x18\x12 \x01(\rR\vwgPeerCount\x12&\n" +
	"\x0fwg_active_peers\x18\x13 \x01(\rR\rwgActivePeers\x12Z\n" +
	"\x0ecustom_metrics\x18\x14 \x03(\v23.aria.agent.MetricsReportRequest.CustomMetricsEntryR\rcustomMetrics\x12\x17\n" +
	"\anode_id\x18\x15 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x16 \x01(\tR\tpublicKey\x1a@\n" +
	"\x12CustomMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"K\n" +
	"\x15MetricsReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb9\x02\n" +
	"\x11ControllerService\x12E\n" +
	"\bRegister\x12\x1b.aria.agent.RegisterRequest\x1a\x1c.aria.agent.RegisterResponse\x129\n" +
	"\x04Sync\x12\x17.aria.agent.SyncRequest\x1a\x18.aria.agent.SyncResponse\x12L\n" +
	"\rCommandStream\x12\x1b.aria.agent.CommandResponse\x1a\x1a.aria.agent.CommandRequest(\x010\x01\x12T\n" +
	"\rReportMetrics\x12 .aria.agent.MetricsReportRequest\x1a!.aria.agent.MetricsReportResponse2\xfb\x01\n" +
	"\fAgentService\x12K\n" +
	"\n" +
	"SyncConfig\x12\x1d.aria.agent.SyncConfigRequest\x1a\x1e.aria.agent.SyncConfigResponse\x12N\n" +
	"\vHealthCheck\x12\x1e.aria.agent.HealthCheckRequest\x1a\x1f.aria.agent.HealthCheckResponse\x12N\n" +
	"\vReportStats\x12\x1e.aria.agent.ReportStatsRequest\x1a\x1f.aria.agent.ReportStatsResponseB\x17Z\x15aria/pkg/grpc/agentpbb\x06proto3"

var (
	file_pkg_grpc_agentpb_aria_agent_proto_rawDescOnce sync.Once
	file_pkg_grpc_agentpb_aria_agent_proto_rawDescData []byte
)

func file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP() []byte {
	file_pkg_grpc_agentpb_aria_agent_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_agentpb_aria_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_agentpb_aria_agent_proto_rawDesc), len(file_pkg_grpc_agentpb_aria_agent_proto_rawDesc)))
	})
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescData
}

var file_pkg_grpc_agentpb_aria_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_pkg_grpc_agentpb_aria_agent_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: aria.agent.RegisterRequest
	(*RegisterResponse)(nil),      // 1: aria.agent.RegisterResponse
	(*SyncRequest)(nil),           // 2: aria.agent.SyncRequest
	(*SyncResponse)(nil),          // 3: aria.agent.SyncResponse
	(*PeerInfo)(nil),              // 4: aria.agent.PeerInfo
	(*ACLRule)(nil),               // 5: aria.agent.ACLRule
	(*QoSRule)(nil),               // 6: aria.agent.QoSRule
	(*BlacklistRule)(nil),         // 7: aria.agent.BlacklistRule
	(*SyncConfigRequest)(nil),     // 8: aria.agent.SyncConfigRequest
	(*SyncConfigResponse)(nil),    // 9: aria.agent.SyncConfigResponse
	(*PeerConfig)(nil),            // 10: aria.agent.PeerConfig
	(*HealthCheckRequest)(nil),    // 11: aria.agent.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 12: aria.agent.HealthCheckResponse
	(*AgentStats)(nil),            // 13: aria.agent.AgentStats
	(*ReportStatsRequest)(nil),    // 14: aria.agent.ReportStatsRequest
	(*ReportStatsResponse)(nil),   // 15: aria.agent.ReportStatsResponse
	(*CommandRequest)(nil),        // 16: aria.agent.CommandRequest
	(*CommandResponse)(nil),       // 17: aria.agent.CommandResponse
	(*MetricsReportRequest)(nil),  // 18: aria.agent.MetricsReportRequest
	(*MetricsReportResponse)(nil), // 19: aria.agent.MetricsReportResponse
	nil,                           // 20: aria.agent.SyncResponse.DomainVersionsEntry
	nil,                           // 21: aria.agent.CommandRequest.ParamsEntry
	nil,                           // 22: aria.agent.CommandResponse.ResultEntry
	nil,                           // 23: aria.agent.MetricsReportRequest.CustomMetricsEntry
}
var file_pkg_grpc_agentpb_aria_agent_proto_depIdxs = []int32{
	4,  // 0: aria.agent.SyncResponse.peers:type_name -> aria.agent.PeerInfo
	5,  // 1: aria.agent.SyncResponse.acl_rules:type_name -> aria.agent.ACLRule
	6,  // 2: aria.agent.SyncResponse.qos_rules:type_name -> aria.agent.QoSRule
	7,  // 3: aria.agent.SyncResponse.blacklist_rules:type_name -> aria.agent.BlacklistRule
	20, // 4: aria.agent.SyncResponse.domain_versions:type_name -> aria.agent.SyncResponse.DomainVersionsEntry
	10, // 5: aria.agent.SyncConfigRequest.peers:type_name -> aria.agent.PeerConfig
	5,  // 6: aria.agent.SyncConfigRequest.acl_rules:type_name -> aria.agent.ACLRule
	6,  // 7: aria.agent.SyncConfigRequest.qos_rules:type_name -> aria.agent.QoSRule
	7,  // 8: aria.agent.SyncConfigRequest.blacklist_rules:type_name -> aria.agent.BlacklistRule
	13, // 9: aria.agent.HealthCheckResponse.stats:type_name -> aria.agent.AgentStats
	13, // 10: aria.agent.ReportStatsRequest.stats:type_name -> aria.agent.AgentStats
	21, // 11: aria.agent.CommandRequest.params:type_name -> aria.agent.CommandRequest.ParamsEntry
	22, // 12: aria.agent.CommandResponse.result:type_name -> aria.agent.CommandResponse.ResultEntry
	23, // 13: aria.agent.MetricsReportRequest.custom_metrics:type_name -> aria.agent.MetricsReportRequest.CustomMetricsEntry
	0,  // 14: aria.agent.ControllerService.Register:input_type -> aria.agent.RegisterRequest
	2,  // 15: aria.agent.ControllerService.Sync:input_type -> aria.agent.SyncRequest
	17, // 16: aria.agent.ControllerService.CommandStream:input_type -> aria.agent.CommandResponse
	18, // 17: aria.agent.ControllerService.ReportMetrics:input_type -> aria.agent.MetricsReportRequest
	8,  // 18: aria.agent.AgentService.SyncConfig:input_type -> aria.agent.SyncConfigRequest
	11, // 19: aria.agent.AgentService.HealthCheck:input_type -> aria.agent.HealthCheckRequest
	14, // 20: aria.agent.AgentService.ReportStats:input_type -> aria.agent.ReportStatsRequest
	1,  // 21: aria.agent.ControllerService.Register:output_type -> aria.agent.RegisterResponse
	3,  // 22: aria.agent.ControllerService.Sync:output_type -> aria.agent.SyncResponse
	16, // 23: aria.agent.ControllerService.CommandStream:output_type -> aria.agent.CommandRequest
	19, // 24: aria.agent.ControllerService.ReportMetrics:output_type -> aria.agent.MetricsReportResponse
	9,  // 25: aria.agent.AgentService.SyncConfig:output_type -> aria.agent.SyncConfigResponse
	12, // 26: aria.agent.AgentService.HealthCheck:output_type -> aria.agent.HealthCheckResponse
	15, // 27: aria.agent.AgentService.ReportStats:output_type -> aria.agent.ReportStatsResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_pkg_grpc_agentpb_aria_agent_proto_init() }
func file_pkg_grpc_agentpb_aria_agent_proto_init() {
	if File_pkg_grpc_agentpb_aria_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_agentpb_aria_agent_proto_rawDesc), len(file_pkg_grpc_agentpb_aria_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_grpc_agentpb_aria_agent_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_agentpb_aria_agent_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_agentpb_aria_agent_proto_msgTypes,
	}.Build()
	File_pkg_grpc_agentpb_aria_agent_proto = out.File
	file_pkg_grpc_agentpb_aria_agent_proto_goTypes = nil
	file_pkg_grpc_agentpb_aria_agent_proto_depIdxs = nil
}
