// Aria Agent gRPC Protocol
// 基于 internal/cli/up.go 中的 REST API 数据结构设计
//
// 通信模式：
// - Controller 监听 :50051 (gRPC)
// - Agent 定期轮询 Sync()（5秒间隔）
// - 支持双向认证（TLS）

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: pkg/grpc/agentpb/aria-agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PublicKey        string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                      // WireGuard 公钥
	Endpoint         string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                                         // 监听地址 ":51820"
	PrivateIp        string                 `protobuf:"bytes,3,opt,name=private_ip,json=privateIp,proto3" json:"private_ip,omitempty"`                      // 内网 IP（可选）
	PublicIp         string                 `protobuf:"bytes,4,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`                         // 公网 IP
	Hostname         string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`                                         // 主机名
	RegisteredAt     int64                  `protobuf:"varint,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`            // 注册时间戳
	Token            string                 `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`                                               // 注册 Token
	AdvertisedRoutes []string               `protobuf:"bytes,8,rep,name=advertised_routes,json=advertisedRoutes,proto3" json:"advertised_routes,omitempty"` // Site-to-Site VPN 路由
	Region           string                 `protobuf:"bytes,9,opt,name=region,proto3" json:"region,omitempty"`                                             // 地域
	CustomerId       string                 `protobuf:"bytes,10,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`                  // 客户 ID
	// 能力检测
	RuntimeMode   string `protobuf:"bytes,11,opt,name=runtime_mode,json=runtimeMode,proto3" json:"runtime_mode,omitempty"`       // "kernel" or "ebpf"
	KernelVersion string `protobuf:"bytes,12,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"` // 内核版本
	HasAesni      bool   `protobuf:"varint,13,opt,name=has_aesni,json=hasAesni,proto3" json:"has_aesni,omitempty"`               // 是否支持 AES-NI
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterRequest) GetPrivateIp() string {
	if x != nil {
		return x.PrivateIp
	}
	return ""
}

func (x *RegisterRequest) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRequest) GetAdvertisedRoutes() []string {
	if x != nil {
		return x.AdvertisedRoutes
	}
	return nil
}

func (x *RegisterRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegisterRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *RegisterRequest) GetRuntimeMode() string {
	if x != nil {
		return x.RuntimeMode
	}
	return ""
}

func (x *RegisterRequest) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *RegisterRequest) GetHasAesni() bool {
	if x != nil {
		return x.HasAesni
	}
	return false
}

type RegisterResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AssignedIp         string                 `protobuf:"bytes,1,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"`                           // 分配的 VPN IP
	MetricsPushGateway string                 `protobuf:"bytes,2,opt,name=metrics_push_gateway,json=metricsPushGateway,proto3" json:"metrics_push_gateway,omitempty"` // Prometheus Push Gateway URL
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}

func (x *RegisterResponse) GetMetricsPushGateway() string {
	if x != nil {
		return x.MetricsPushGateway
	}
	return ""
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // 用于认证（替代 X-Public-Key header）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{2}
}

func (x *SyncRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type SyncResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Peers              []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`                                                       // WireGuard Peers 列表
	AssignedIp         string                 `protobuf:"bytes,2,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"`                           // 当前节点的 VPN IP
	LastUpdate         int64                  `protobuf:"varint,3,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`                          // 最后更新时间戳
	AclRules           []*ACLRule             `protobuf:"bytes,4,rep,name=acl_rules,json=aclRules,proto3" json:"acl_rules,omitempty"`                                 // 防火墙 ACL 规则
	MetricsPushGateway string                 `protobuf:"bytes,5,opt,name=metrics_push_gateway,json=metricsPushGateway,proto3" json:"metrics_push_gateway,omitempty"` // Prometheus Push Gateway URL
	// 未来扩展字段
	QosRules      []*QoSRule `protobuf:"bytes,6,rep,name=qos_rules,json=qosRules,proto3" json:"qos_rules,omitempty"` // QoS 限速规则（预留）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{3}
}

func (x *SyncResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *SyncResponse) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}

func (x *SyncResponse) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

func (x *SyncResponse) GetAclRules() []*ACLRule {
	if x != nil {
		return x.AclRules
	}
	return nil
}

func (x *SyncResponse) GetMetricsPushGateway() string {
	if x != nil {
		return x.MetricsPushGateway
	}
	return ""
}

func (x *SyncResponse) GetQosRules() []*QoSRule {
	if x != nil {
		return x.QosRules
	}
	return nil
}

type PeerInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PublicKey        string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                       // WireGuard 公钥
	Endpoint         string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                                          // UDP 端点地址
	PrivateIp        string                 `protobuf:"bytes,3,opt,name=private_ip,json=privateIp,proto3" json:"private_ip,omitempty"`                       // 内网 IP
	PublicIp         string                 `protobuf:"bytes,4,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`                          // 公网 IP
	Region           string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`                                              // 地域
	VpcId            string                 `protobuf:"bytes,6,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`                                   // VPC ID
	Hostname         string                 `protobuf:"bytes,7,opt,name=hostname,proto3" json:"hostname,omitempty"`                                          // 主机名
	AssignedIp       string                 `protobuf:"bytes,8,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"`                    // VPN IP
	Role             string                 `protobuf:"bytes,9,opt,name=role,proto3" json:"role,omitempty"`                                                  // 角色
	AdvertisedRoutes []string               `protobuf:"bytes,10,rep,name=advertised_routes,json=advertisedRoutes,proto3" json:"advertised_routes,omitempty"` // Site-to-Site VPN 路由
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PeerInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *PeerInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PeerInfo) GetPrivateIp() string {
	if x != nil {
		return x.PrivateIp
	}
	return ""
}

func (x *PeerInfo) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *PeerInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PeerInfo) GetVpcId() string {
	if x != nil {
		return x.VpcId
	}
	return ""
}

func (x *PeerInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PeerInfo) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}

func (x *PeerInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PeerInfo) GetAdvertisedRoutes() []string {
	if x != nil {
		return x.AdvertisedRoutes
	}
	return nil
}

type ACLRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcNet        string                 `protobuf:"bytes,1,opt,name=src_net,json=srcNet,proto3" json:"src_net,omitempty"`     // 源 CIDR（如 "10.0.0.0/8"）
	DstNet        string                 `protobuf:"bytes,2,opt,name=dst_net,json=dstNet,proto3" json:"dst_net,omitempty"`     // 目标 CIDR（如 "192.168.0.0/16"）
	Protocol      uint32                 `protobuf:"varint,3,opt,name=protocol,proto3" json:"protocol,omitempty"`              // IP 协议（6=TCP, 17=UDP, 0=any）
	MinPort       uint32                 `protobuf:"varint,4,opt,name=min_port,json=minPort,proto3" json:"min_port,omitempty"` // 最小端口（0=any）
	MaxPort       uint32                 `protobuf:"varint,5,opt,name=max_port,json=maxPort,proto3" json:"max_port,omitempty"` // 最大端口（65535=any）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACLRule) Reset() {
	*x = ACLRule{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACLRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACLRule) ProtoMessage() {}

func (x *ACLRule) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACLRule.ProtoReflect.Descriptor instead.
func (*ACLRule) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ACLRule) GetSrcNet() string {
	if x != nil {
		return x.SrcNet
	}
	return ""
}

func (x *ACLRule) GetDstNet() string {
	if x != nil {
		return x.DstNet
	}
	return ""
}

func (x *ACLRule) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *ACLRule) GetMinPort() uint32 {
	if x != nil {
		return x.MinPort
	}
	return 0
}

func (x *ACLRule) GetMaxPort() uint32 {
	if x != nil {
		return x.MaxPort
	}
	return 0
}

type QoSRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIp         string                 `protobuf:"bytes,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`                          // 源 IP
	DstIp         string                 `protobuf:"bytes,2,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`                          // 目标 IP
	SrcPort       uint32                 `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`                   // 源端口
	DstPort       uint32                 `protobuf:"varint,4,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`                   // 目标端口
	Protocol      uint32                 `protobuf:"varint,5,opt,name=protocol,proto3" json:"protocol,omitempty"`                                // 协议
	BandwidthMbps uint64                 `protobuf:"varint,6,opt,name=bandwidth_mbps,json=bandwidthMbps,proto3" json:"bandwidth_mbps,omitempty"` // 带宽限制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QoSRule) Reset() {
	*x = QoSRule{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QoSRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QoSRule) ProtoMessage() {}

func (x *QoSRule) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QoSRule.ProtoReflect.Descriptor instead.
func (*QoSRule) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{6}
}

func (x *QoSRule) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *QoSRule) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *QoSRule) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *QoSRule) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *QoSRule) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *QoSRule) GetBandwidthMbps() uint64 {
	if x != nil {
		return x.BandwidthMbps
	}
	return 0
}

type SyncConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerConfig          `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`                       // Peer 配置
	AclRules      []*ACLRule             `protobuf:"bytes,2,rep,name=acl_rules,json=aclRules,proto3" json:"acl_rules,omitempty"` // ACL 规则
	QosRules      []*QoSRule             `protobuf:"bytes,3,rep,name=qos_rules,json=qosRules,proto3" json:"qos_rules,omitempty"` // QoS 规则
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncConfigRequest) Reset() {
	*x = SyncConfigRequest{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConfigRequest) ProtoMessage() {}

func (x *SyncConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConfigRequest.ProtoReflect.Descriptor instead.
func (*SyncConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{7}
}

func (x *SyncConfigRequest) GetPeers() []*PeerConfig {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *SyncConfigRequest) GetAclRules() []*ACLRule {
	if x != nil {
		return x.AclRules
	}
	return nil
}

func (x *SyncConfigRequest) GetQosRules() []*QoSRule {
	if x != nil {
		return x.QosRules
	}
	return nil
}

type SyncConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncConfigResponse) Reset() {
	*x = SyncConfigResponse{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConfigResponse) ProtoMessage() {}

func (x *SyncConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConfigResponse.ProtoReflect.Descriptor instead.
func (*SyncConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{8}
}

func (x *SyncConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PeerConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PublicKey           string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Endpoint            string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AllowedIps          []string               `protobuf:"bytes,3,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	PersistentKeepalive uint32                 `protobuf:"varint,4,opt,name=persistent_keepalive,json=persistentKeepalive,proto3" json:"persistent_keepalive,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PeerConfig) Reset() {
	*x = PeerConfig{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerConfig) ProtoMessage() {}

func (x *PeerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerConfig.ProtoReflect.Descriptor instead.
func (*PeerConfig) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{9}
}

func (x *PeerConfig) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *PeerConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PeerConfig) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *PeerConfig) GetPersistentKeepalive() uint32 {
	if x != nil {
		return x.PersistentKeepalive
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Stats         *AgentStats            `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{11}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetStats() *AgentStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type AgentStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalPeers    uint64                 `protobuf:"varint,1,opt,name=total_peers,json=totalPeers,proto3" json:"total_peers,omitempty"`     // 总 Peer 数
	ActivePeers   uint64                 `protobuf:"varint,2,opt,name=active_peers,json=activePeers,proto3" json:"active_peers,omitempty"`  // 活跃 Peer 数
	CpuUsage      float64                `protobuf:"fixed64,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`          // CPU 使用率
	MemoryUsage   float64                `protobuf:"fixed64,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"` // 内存使用率
	TxBytes       uint64                 `protobuf:"varint,5,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`              // 发送字节数
	RxBytes       uint64                 `protobuf:"varint,6,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`              // 接收字节数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStats) Reset() {
	*x = AgentStats{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStats) ProtoMessage() {}

func (x *AgentStats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStats.ProtoReflect.Descriptor instead.
func (*AgentStats) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{12}
}

func (x *AgentStats) GetTotalPeers() uint64 {
	if x != nil {
		return x.TotalPeers
	}
	return 0
}

func (x *AgentStats) GetActivePeers() uint64 {
	if x != nil {
		return x.ActivePeers
	}
	return 0
}

func (x *AgentStats) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *AgentStats) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *AgentStats) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *AgentStats) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

type ReportStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Stats         *AgentStats            `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatsRequest) Reset() {
	*x = ReportStatsRequest{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatsRequest) ProtoMessage() {}

func (x *ReportStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatsRequest.ProtoReflect.Descriptor instead.
func (*ReportStatsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ReportStatsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReportStatsRequest) GetStats() *AgentStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type ReportStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatsResponse) Reset() {
	*x = ReportStatsResponse{}
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatsResponse) ProtoMessage() {}

func (x *ReportStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_agentpb_aria_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatsResponse.ProtoReflect.Descriptor instead.
func (*ReportStatsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ReportStatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pkg_grpc_agentpb_aria_agent_proto protoreflect.FileDescriptor

const file_pkg_grpc_agentpb_aria_agent_proto_rawDesc = "" +
	"\n" +
	"!pkg/grpc/agentpb/aria-agent.proto\x12\n" +
	"aria.agent\"\xac\x03\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1d\n" +
	"\n" +
	"private_ip\x18\x03 \x01(\tR\tprivateIp\x12\x1b\n" +
	"\tpublic_ip\x18\x04 \x01(\tR\bpublicIp\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12#\n" +
	"\rregistered_at\x18\x06 \x01(\x03R\fregisteredAt\x12\x14\n" +
	"\x05token\x18\a \x01(\tR\x05token\x12+\n" +
	"\x11advertised_routes\x18\b \x03(\tR\x10advertisedRoutes\x12\x16\n" +
	"\x06region\x18\t \x01(\tR\x06region\x12\x1f\n" +
	"\vcustomer_id\x18\n" +
	" \x01(\tR\n" +
	"customerId\x12!\n" +
	"\fruntime_mode\x18\v \x01(\tR\vruntimeMode\x12%\n" +
	"\x0ekernel_version\x18\f \x01(\tR\rkernelVersion\x12\x1b\n" +
	"\thas_aesni\x18\r \x01(\bR\bhasAesni\"e\n" +
	"\x10RegisterResponse\x12\x1f\n" +
	"\vassigned_ip\x18\x01 \x01(\tR\n" +
	"assignedIp\x120\n" +
	"\x14metrics_push_gateway\x18\x02 \x01(\tR\x12metricsPushGateway\",\n" +
	"\vSyncRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\"\x92\x02\n" +
	"\fSyncResponse\x12*\n" +
	"\x05peers\x18\x01 \x03(\v2\x14.aria.agent.PeerInfoR\x05peers\x12\x1f\n" +
	"\vassigned_ip\x18\x02 \x01(\tR\n" +
	"assignedIp\x12\x1f\n" +
	"\vlast_update\x18\x03 \x01(\x03R\n" +
	"lastUpdate\x120\n" +
	"\tacl_rules\x18\x04 \x03(\v2\x13.aria.agent.ACLRuleR\baclRules\x120\n" +
	"\x14metrics_push_gateway\x18\x05 \x01(\tR\x12metricsPushGateway\x120\n" +
	"\tqos_rules\x18\x06 \x03(\v2\x13.aria.agent.QoSRuleR\bqosRules\"\xae\x02\n" +
	"\bPeerInfo\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1d\n" +
	"\n" +
	"private_ip\x18\x03 \x01(\tR\tprivateIp\x12\x1b\n" +
	"\tpublic_ip\x18\x04 \x01(\tR\bpublicIp\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x15\n" +
	"\x06vpc_id\x18\x06 \x01(\tR\x05vpcId\x12\x1a\n" +
	"\bhostname\x18\a \x01(\tR\bhostname\x12\x1f\n" +
	"\vassigned_ip\x18\b \x01(\tR\n" +
	"assignedIp\x12\x12\n" +
	"\x04role\x18\t \x01(\tR\x04role\x12+\n" +
	"\x11advertised_routes\x18\n" +
	" \x03(\tR\x10advertisedRoutes\"\x8d\x01\n" +
	"\aACLRule\x12\x17\n" +
	"\asrc_net\x18\x01 \x01(\tR\x06srcNet\x12\x17\n" +
	"\adst_net\x18\x02 \x01(\tR\x06dstNet\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\rR\bprotocol\x12\x19\n" +
	"\bmin_port\x18\x04 \x01(\rR\aminPort\x12\x19\n" +
	"\bmax_port\x18\x05 \x01(\rR\amaxPort\"\xb0\x01\n" +
	"\aQoSRule\x12\x15\n" +
	"\x06src_ip\x18\x01 \x01(\tR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x02 \x01(\tR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x03 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x04 \x01(\rR\adstPort\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\rR\bprotocol\x12%\n" +
	"\x0ebandwidth_mbps\x18\x06 \x01(\x04R\rbandwidthMbps\"\xa5\x01\n" +
	"\x11SyncConfigRequest\x12,\n" +
	"\x05peers\x18\x01 \x03(\v2\x16.aria.agent.PeerConfigR\x05peers\x120\n" +
	"\tacl_rules\x18\x02 \x03(\v2\x13.aria.agent.ACLRuleR\baclRules\x120\n" +
	"\tqos_rules\x18\x03 \x03(\v2\x13.aria.agent.QoSRuleR\bqosRules\"H\n" +
	"\x12SyncConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9b\x01\n" +
	"\n" +
	"PeerConfig\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\x03 \x03(\tR\n" +
	"allowedIps\x121\n" +
	"\x14persistent_keepalive\x18\x04 \x01(\rR\x13persistentKeepalive\"/\n" +
	"\x12HealthCheckRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"w\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x05stats\x18\x03 \x01(\v2\x16.aria.agent.AgentStatsR\x05stats\"\xc6\x01\n" +
	"\n" +
	"AgentStats\x12\x1f\n" +
	"\vtotal_peers\x18\x01 \x01(\x04R\n" +
	"totalPeers\x12!\n" +
	"\factive_peers\x18\x02 \x01(\x04R\vactivePeers\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\x01R\vmemoryUsage\x12\x19\n" +
	"\btx_bytes\x18\x05 \x01(\x04R\atxBytes\x12\x19\n" +
	"\brx_bytes\x18\x06 \x01(\x04R\arxBytes\"]\n" +
	"\x12ReportStatsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12,\n" +
	"\x05stats\x18\x02 \x01(\v2\x16.aria.agent.AgentStatsR\x05stats\"/\n" +
	"\x13ReportStatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x95\x01\n" +
	"\x11ControllerService\x12E\n" +
	"\bRegister\x12\x1b.aria.agent.RegisterRequest\x1a\x1c.aria.agent.RegisterResponse\x129\n" +
	"\x04Sync\x12\x17.aria.agent.SyncRequest\x1a\x18.aria.agent.SyncResponse2\xfb\x01\n" +
	"\fAgentService\x12K\n" +
	"\n" +
	"SyncConfig\x12\x1d.aria.agent.SyncConfigRequest\x1a\x1e.aria.agent.SyncConfigResponse\x12N\n" +
	"\vHealthCheck\x12\x1e.aria.agent.HealthCheckRequest\x1a\x1f.aria.agent.HealthCheckResponse\x12N\n" +
	"\vReportStats\x12\x1e.aria.agent.ReportStatsRequest\x1a\x1f.aria.agent.ReportStatsResponseB\x17Z\x15aria/pkg/grpc/agentpbb\x06proto3"

var (
	file_pkg_grpc_agentpb_aria_agent_proto_rawDescOnce sync.Once
	file_pkg_grpc_agentpb_aria_agent_proto_rawDescData []byte
)

func file_pkg_grpc_agentpb_aria_agent_proto_rawDescGZIP() []byte {
	file_pkg_grpc_agentpb_aria_agent_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_agentpb_aria_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_agentpb_aria_agent_proto_rawDesc), len(file_pkg_grpc_agentpb_aria_agent_proto_rawDesc)))
	})
	return file_pkg_grpc_agentpb_aria_agent_proto_rawDescData
}

var file_pkg_grpc_agentpb_aria_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pkg_grpc_agentpb_aria_agent_proto_goTypes = []any{
	(*RegisterRequest)(nil),     // 0: aria.agent.RegisterRequest
	(*RegisterResponse)(nil),    // 1: aria.agent.RegisterResponse
	(*SyncRequest)(nil),         // 2: aria.agent.SyncRequest
	(*SyncResponse)(nil),        // 3: aria.agent.SyncResponse
	(*PeerInfo)(nil),            // 4: aria.agent.PeerInfo
	(*ACLRule)(nil),             // 5: aria.agent.ACLRule
	(*QoSRule)(nil),             // 6: aria.agent.QoSRule
	(*SyncConfigRequest)(nil),   // 7: aria.agent.SyncConfigRequest
	(*SyncConfigResponse)(nil),  // 8: aria.agent.SyncConfigResponse
	(*PeerConfig)(nil),          // 9: aria.agent.PeerConfig
	(*HealthCheckRequest)(nil),  // 10: aria.agent.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 11: aria.agent.HealthCheckResponse
	(*AgentStats)(nil),          // 12: aria.agent.AgentStats
	(*ReportStatsRequest)(nil),  // 13: aria.agent.ReportStatsRequest
	(*ReportStatsResponse)(nil), // 14: aria.agent.ReportStatsResponse
}
var file_pkg_grpc_agentpb_aria_agent_proto_depIdxs = []int32{
	4,  // 0: aria.agent.SyncResponse.peers:type_name -> aria.agent.PeerInfo
	5,  // 1: aria.agent.SyncResponse.acl_rules:type_name -> aria.agent.ACLRule
	6,  // 2: aria.agent.SyncResponse.qos_rules:type_name -> aria.agent.QoSRule
	9,  // 3: aria.agent.SyncConfigRequest.peers:type_name -> aria.agent.PeerConfig
	5,  // 4: aria.agent.SyncConfigRequest.acl_rules:type_name -> aria.agent.ACLRule
	6,  // 5: aria.agent.SyncConfigRequest.qos_rules:type_name -> aria.agent.QoSRule
	12, // 6: aria.agent.HealthCheckResponse.stats:type_name -> aria.agent.AgentStats
	12, // 7: aria.agent.ReportStatsRequest.stats:type_name -> aria.agent.AgentStats
	0,  // 8: aria.agent.ControllerService.Register:input_type -> aria.agent.RegisterRequest
	2,  // 9: aria.agent.ControllerService.Sync:input_type -> aria.agent.SyncRequest
	7,  // 10: aria.agent.AgentService.SyncConfig:input_type -> aria.agent.SyncConfigRequest
	10, // 11: aria.agent.AgentService.HealthCheck:input_type -> aria.agent.HealthCheckRequest
	13, // 12: aria.agent.AgentService.ReportStats:input_type -> aria.agent.ReportStatsRequest
	1,  // 13: aria.agent.ControllerService.Register:output_type -> aria.agent.RegisterResponse
	3,  // 14: aria.agent.ControllerService.Sync:output_type -> aria.agent.SyncResponse
	8,  // 15: aria.agent.AgentService.SyncConfig:output_type -> aria.agent.SyncConfigResponse
	11, // 16: aria.agent.AgentService.HealthCheck:output_type -> aria.agent.HealthCheckResponse
	14, // 17: aria.agent.AgentService.ReportStats:output_type -> aria.agent.ReportStatsResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_grpc_agentpb_aria_agent_proto_init() }
func file_pkg_grpc_agentpb_aria_agent_proto_init() {
	if File_pkg_grpc_agentpb_aria_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_agentpb_aria_agent_proto_rawDesc), len(file_pkg_grpc_agentpb_aria_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_grpc_agentpb_aria_agent_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_agentpb_aria_agent_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_agentpb_aria_agent_proto_msgTypes,
	}.Build()
	File_pkg_grpc_agentpb_aria_agent_proto = out.File
	file_pkg_grpc_agentpb_aria_agent_proto_goTypes = nil
	file_pkg_grpc_agentpb_aria_agent_proto_depIdxs = nil
}
