package cli

import (
	"bufio"
	"fmt"
	"os"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
)

var controllerInitCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize controller configuration",
	Long: `Initialize the Aria Controller configuration and deployment files.

Modes:
  local - Deploy PostgreSQL and Redis as local Docker containers
          Best for: testing, development, small deployments

  cloud - Use cloud-managed database services (RDS, ElastiCache, etc.)
          Best for: production, high availability requirements

This command generates:
  - /etc/aria/controller.yaml - Controller configuration
  - /etc/aria/docker-compose.yaml - Docker Compose file for deployment

Examples:
  aria controller init --mode=local
  aria controller init --mode=cloud`,
	RunE: runControllerInit,
}

var initMode string

func init() {
	controllerCmd.AddCommand(controllerInitCmd)
	controllerInitCmd.Flags().StringVar(&initMode, "mode", "", "Deployment mode: local or cloud")
}

func runControllerInit(cmd *cobra.Command, args []string) error {
	// Check if running as root
	if os.Geteuid() != 0 {
		return fmt.Errorf("this command must be run as root")
	}

	// If mode not specified, prompt user
	if initMode == "" {
		fmt.Println("Select deployment mode:")
		fmt.Println("  1) local  - Deploy PostgreSQL + Redis as Docker containers (for testing)")
		fmt.Println("  2) cloud  - Use cloud-managed services like RDS (for production)")
		fmt.Print("\nChoice [1/2]: ")

		reader := bufio.NewReader(os.Stdin)
		choice, _ := reader.ReadString('\n')
		choice = strings.TrimSpace(choice)

		switch choice {
		case "1", "local":
			initMode = "local"
		case "2", "cloud":
			initMode = "cloud"
		default:
			return fmt.Errorf("invalid choice: %s", choice)
		}
	}

	// Ensure config directory exists
	if err := os.MkdirAll("/etc/aria", 0755); err != nil {
		return fmt.Errorf("failed to create /etc/aria: %w", err)
	}

	switch initMode {
	case "local":
		return initLocalMode()
	case "cloud":
		return initCloudMode()
	default:
		return fmt.Errorf("invalid mode: %s (use 'local' or 'cloud')", initMode)
	}
}

func initLocalMode() error {
	fmt.Println("\nInitializing LOCAL mode...")
	fmt.Println()

	// Generate controller.yaml
	controllerConfig := `# Aria Controller Configuration
# Generated by 'aria controller init --mode=local'

server:
  host: "0.0.0.0"
  port: 8080

storage:
  postgres:
    host: "postgres"
    port: 5432
    user: "aria"
    password: ""
    database: "aria"
    sslmode: "disable"
  redis:
    addr: "redis:6379"
    password: ""

network:
  base_ip: "100.64.0.0"
  cidr: "100.64.0.0/16"

jwt:
  secret: "CHANGE-ME-TO-A-RANDOM-32-BYTE-STRING"

logging:
  level: "info"
  dir: "/var/log/aria"
`

	if err := os.WriteFile("/etc/aria/controller.yaml", []byte(controllerConfig), 0600); err != nil {
		return fmt.Errorf("failed to write controller.yaml: %w", err)
	}
	fmt.Println("Created: /etc/aria/controller.yaml")

	// Generate docker-compose.yaml
	dockerCompose := `# Aria Controller Docker Compose
# Generated by 'aria controller init --mode=local'

version: '3.8'

services:
  controller:
    image: aria-controller:latest
    container_name: aria_controller
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./controller.yaml:/etc/aria/controller.yaml:ro
      - aria-logs:/var/log/aria
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=aria
      - POSTGRES_PASSWORD=
      - POSTGRES_DATABASE=aria
      - REDIS_ADDR=redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - aria-network

  postgres:
    image: postgres:15-alpine
    container_name: aria_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=aria
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=aria
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aria -d aria"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - aria-network

  redis:
    image: redis:7-alpine
    container_name: aria_redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - aria-network

volumes:
  postgres-data:
  redis-data:
  aria-logs:

networks:
  aria-network:
    driver: bridge
`

	if err := os.WriteFile("/etc/aria/docker-compose.yaml", []byte(dockerCompose), 0644); err != nil {
		return fmt.Errorf("failed to write docker-compose.yaml: %w", err)
	}
	fmt.Println("Created: /etc/aria/docker-compose.yaml")

	fmt.Println()
	fmt.Println("Local mode initialization complete!")
	fmt.Println()
	fmt.Println("Next steps:")
	fmt.Println("  1. Build controller image:")
	fmt.Println("     make release-deploy")
	fmt.Println("     docker load -i releases/deploy/controller/images/aria-controller.tar")
	fmt.Println()
	fmt.Println("  2. Start services:")
	fmt.Println("     cd /etc/aria && docker-compose up -d")
	fmt.Println()
	fmt.Println("  3. Create enrollment token:")
	fmt.Println("     docker exec aria_controller aria token create --tag=my-first-token")
	fmt.Println()

	return nil
}

func initCloudMode() error {
	fmt.Println("\nInitializing CLOUD mode...")
	fmt.Println()

	reader := bufio.NewReader(os.Stdin)

	// Prompt for PostgreSQL settings
	fmt.Println("PostgreSQL Configuration")
	fmt.Println(strings.Repeat("-", 40))

	fmt.Print("Host (e.g., pgm-xxx.pg.rds.aliyuncs.com): ")
	pgHost, _ := reader.ReadString('\n')
	pgHost = strings.TrimSpace(pgHost)
	if pgHost == "" {
		return fmt.Errorf("PostgreSQL host is required")
	}

	fmt.Print("Port [5432]: ")
	pgPort, _ := reader.ReadString('\n')
	pgPort = strings.TrimSpace(pgPort)
	if pgPort == "" {
		pgPort = "5432"
	}

	fmt.Print("User: ")
	pgUser, _ := reader.ReadString('\n')
	pgUser = strings.TrimSpace(pgUser)
	if pgUser == "" {
		return fmt.Errorf("PostgreSQL user is required")
	}

	fmt.Print("Password: ")
	pgPassword, _ := reader.ReadString('\n')
	pgPassword = strings.TrimSpace(pgPassword)

	fmt.Print("Database [aria]: ")
	pgDatabase, _ := reader.ReadString('\n')
	pgDatabase = strings.TrimSpace(pgDatabase)
	if pgDatabase == "" {
		pgDatabase = "aria"
	}

	fmt.Print("SSL Mode [require]: ")
	pgSSLMode, _ := reader.ReadString('\n')
	pgSSLMode = strings.TrimSpace(pgSSLMode)
	if pgSSLMode == "" {
		pgSSLMode = "require"
	}

	fmt.Println()

	// Prompt for Redis settings
	fmt.Println("Redis Configuration")
	fmt.Println(strings.Repeat("-", 40))

	fmt.Print("Host (e.g., r-xxx.redis.rds.aliyuncs.com): ")
	redisHost, _ := reader.ReadString('\n')
	redisHost = strings.TrimSpace(redisHost)
	if redisHost == "" {
		return fmt.Errorf("Redis host is required")
	}

	fmt.Print("Port [6379]: ")
	redisPort, _ := reader.ReadString('\n')
	redisPort = strings.TrimSpace(redisPort)
	if redisPort == "" {
		redisPort = "6379"
	}

	fmt.Print("Password: ")
	redisPassword, _ := reader.ReadString('\n')
	redisPassword = strings.TrimSpace(redisPassword)

	fmt.Println()
	fmt.Print("Testing connections... ")

	// TODO: Actually test connections
	fmt.Println("(skipped)")

	// Generate config using template
	configTmpl := `# Aria Controller Configuration
# Generated by 'aria controller init --mode=cloud'

server:
  host: "0.0.0.0"
  port: 8080

storage:
  postgres:
    host: "{{.PgHost}}"
    port: {{.PgPort}}
    user: "{{.PgUser}}"
    password: "{{.PgPassword}}"
    database: "{{.PgDatabase}}"
    sslmode: "{{.PgSSLMode}}"
  redis:
    addr: "{{.RedisHost}}:{{.RedisPort}}"
    password: "{{.RedisPassword}}"

network:
  base_ip: "100.64.0.0"
  cidr: "100.64.0.0/16"

jwt:
  secret: "CHANGE-ME-TO-A-RANDOM-32-BYTE-STRING"

logging:
  level: "info"
  dir: "/var/log/aria"
`

	data := map[string]string{
		"PgHost":        pgHost,
		"PgPort":        pgPort,
		"PgUser":        pgUser,
		"PgPassword":    pgPassword,
		"PgDatabase":    pgDatabase,
		"PgSSLMode":     pgSSLMode,
		"RedisHost":     redisHost,
		"RedisPort":     redisPort,
		"RedisPassword": redisPassword,
	}

	tmpl, err := template.New("config").Parse(configTmpl)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	f, err := os.OpenFile("/etc/aria/controller.yaml", os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return fmt.Errorf("failed to create controller.yaml: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("failed to write controller.yaml: %w", err)
	}
	fmt.Println("Created: /etc/aria/controller.yaml")

	// Generate docker-compose.yaml (controller only)
	dockerCompose := `# Aria Controller Docker Compose (Cloud Mode)
# Generated by 'aria controller init --mode=cloud'
# Uses external PostgreSQL and Redis services

version: '3.8'

services:
  controller:
    image: aria-controller:latest
    container_name: aria_controller
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./controller.yaml:/etc/aria/controller.yaml:ro
      - aria-logs:/var/log/aria
    networks:
      - aria-network

volumes:
  aria-logs:

networks:
  aria-network:
    driver: bridge
`

	if err := os.WriteFile("/etc/aria/docker-compose.yaml", []byte(dockerCompose), 0644); err != nil {
		return fmt.Errorf("failed to write docker-compose.yaml: %w", err)
	}
	fmt.Println("Created: /etc/aria/docker-compose.yaml")

	fmt.Println()
	fmt.Println("Cloud mode initialization complete!")
	fmt.Println()
	fmt.Println("Next steps:")
	fmt.Println("  1. Build controller image:")
	fmt.Println("     make release-deploy")
	fmt.Println("     docker load -i releases/deploy/controller/images/aria-controller.tar")
	fmt.Println()
	fmt.Println("  2. Start controller:")
	fmt.Println("     cd /etc/aria && docker-compose up -d")
	fmt.Println()
	fmt.Println("  3. Create enrollment token:")
	fmt.Println("     docker exec aria_controller aria token create --tag=my-first-token")
	fmt.Println()

	return nil
}
