export type Permission =
  | '*'
  | 'nodes:read'
  | 'nodes:write'
  | 'routes:read'
  | 'routes:write'
  | 'acls:read'
  | 'acls:write'
  | 'ip-groups:read'
  | 'ip-groups:write'
  | 'qos:read'
  | 'qos:write'
  | 'blacklist:read'
  | 'blacklist:write'
  | 'monitoring:read'
  | 'commands:write'
  | 'tokens:read'
  | 'tokens:write'
  | 'users:read'
  | 'users:write'
  | 'roles:read'
  | 'roles:write'
  | 'ai:use'
  | 'policies:read'
  | 'settings:read'
  | 'settings:write'

export type RoleName = 'super_admin' | 'admin' | 'operator' | 'viewer'

