pub mod acl;
pub mod qos;
pub mod identity;
pub mod grpc_client;
pub mod wireguard;
pub mod routing;
pub mod config;
pub mod metrics;
pub mod system_optimization;
pub mod runtime_credential;
pub mod sync_apply;

pub use acl::{AclManager, AclError, PolicyKey, PolicyValue, ACTION_DROP, ACTION_PASS};
pub use qos::{QoSManager, QoSError, BucketState, ServiceQoSKey, PairQoSKey};
pub use identity::{IdentityManager, IdentityError, CidrEntry, ID_WILDCARD};
pub use grpc_client::{GrpcClient, SyncResult, PeerInfo, AclRule};
pub use wireguard::{WireGuardManager, WireGuardError};
pub use routing::{RoutingManager, RouteError, RouteEntry};
pub use config::{ConfigManager, AgentConfig, BootstrapConfig, AgentState};
pub use metrics::{MetricsCounters, record_agent_uptime};
pub use system_optimization::{SystemOptimizer, OptimizationResult};
